blank_issues_enabled: false
contact_links:
  - name: Enhancement Request
    url: https://github.com/pieces-app/support/discussions
    about: Post your idea for Pieces awesome-repo in discussions for the Pieces team and community to discuss!
